### PR TITLE
Shadow DOM slots, composition

### PR DESCRIPTION
**Pull request by abdmmar**
Selesai terjemah `Shadow DOM slots, composition`, mohon untuk direview, terima kasih.

### CODE REVIEW

**Comment by yoga1234** [comment]
_This pull request is still a work in progress_ . Belum bereskah?

**Comment by abdmmar** [comment]
> _This pull request is still a work in progress_ . Belum bereskah?

Sudah mas 👍

**Comment by yoga1234** [comment]
Ini buat hacktoberfest?

**Review by yoga1234 — APPROVED** [review]
LGTM!

**Comment by abdmmar** [comment]
> LGTM!

Terima kasih mas Yoga

**Pull request merged**
